### ISSUE TITLE
[2.5.1] This program must be run under the AutoHotkey_L (AHK_Lw) build of AutoHotkey

### ISSUE THREAD

**Issue by isaak654** [blap/SandboxToys2#11]
Error dialog after running [v2.5.1](https://github.com/blap/SandboxToys2/releases/tag/v2.5.1) in the Sandboxie Plus folder:

![Error_SandboxToys2_2.5.1](https://github.com/blap/SandboxToys2/assets/12372772/7aee6849-bfc2-4693-80f3-71a4f7c91f86)

https://github.com/blap/SandboxToys2/blob/e7a29a96176813e21adb136a6272202bcfbde668/SandboxToys2.ahk#L149-L151

**Comment by isaak654** [comment]
@blap It looks like a build error to me, hopefully it can be reuploaded.

**Comment by blap** [comment]
My bad.
Reuploaded.
