### ISSUE TITLE
SandboxToys2 cannot detect any sandbox with a custom FileRootPath

### ISSUE THREAD

**Issue by isaak654** [blap/SandboxToys2#12]
SandboxToys2 cannot detect any of my dozen sandboxes and it erroneously display DefaultBox as empty (when it isn't):

![SandboxToys2 without sandbox list](https://github.com/blap/SandboxToys2/assets/12372772/ef1922cd-4f87-486c-ac52-a194bdaece4c)

The only workaround for me is to remove `FileRootPath=F:\Sandbox\%USER%\%SANDBOX%` and let Sandboxie Plus create `C:\Sandbox\User\DefaultBox` by running any sandboxed program in it... in this case, there will be additional entries like Explore, Registry, Tools:

![SandboxToys2 with only DefaultBox in the list](https://github.com/blap/SandboxToys2/assets/12372772/fb1c64fd-59c6-4b1d-a653-fac71c002ac5)

If I apply this workaround for the other sandboxes one by one, unfortunately SandboxToys2 will still continue to detect only DefaultBox as in the second image - maybe some extra effort is needed here, not sure `¯\_(ツ)_/¯`

System configuration and additional notes:
- Windows 10 Pro x64 22H2
- I can reproduce this with any SandboxToys2 version (the latest release as much as the first release)
- I downgraded my Sandboxie Plus version from 1.9.6 to 1.8.4 and from 1.8.4 to 1.6.7, but it didn't make any difference
- My Sandboxie.ini is in `C:\Program Files\Sandboxie-Plus`

Sandboxie.ini configuration:

```
[GlobalSettings]
FileRootPath=F:\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
TraceBufferPages=2560
TemplateReject=7zipShellEx
TemplateReject=RTSS
TemplateReject=WindowsRasMan
TemplateReject=WindowsLive
DefaultBox=DefaultBox
```

Note: removing `DefaultBox=DefaultBox` doesn't make a difference.

**Comment by isaak654** [comment]
It doesn't work for me in the new version, see https://github.com/blap/SandboxToys2/pull/13#issuecomment-1719927335

**Comment by offhub** [comment]
Is it portable installation?
Is there another Sandboxie.ini file located under `%windir%`?

**Comment by isaak654** [comment]
> Is there another Sandboxie.ini file located under `%windir%`?

Sorry, I forgot to remove it after testing it, and now the issue is fixed for me too. 
Thank you!

**Comment by isaak654** [comment]
> Is there another Sandboxie.ini file located under `%windir%`?

I forgot to remove it after testing it, and now the issue is fixed for me too. 
Thank you!
