### ISSUE TITLE
Outdated download links

### ISSUE THREAD

**Issue by Koakuma-spec** [blap/SandboxToys2#5]
Hi, just letting you know that the links in the [original forum](https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopic33fc33fc.html?f=22&t=2028) are outdated. They contain the .exe files, but the [first link](http://home.base.be/vt6328799/SandboxToys.zip) does not work and the [second link](http://download.videohelp.com/r0lZ/SandboxToys.zip) warns me that it cannot be downloaded securely.

Maybe there should be an .exe file on a new host?

**Comment by isaak654** [comment]
The original link at the beginning of the [README.md](https://github.com/blap/SandboxToys2#readme) was included to mention the original discussion from which SandboxToys2 originated. At most, that part could be improved to avoid misunderstandings.

If you want to download the latest release: https://github.com/blap/SandboxToys2/releases 
The same link can be found manually from the [right column](https://user-images.githubusercontent.com/12372772/228072872-0d1ab51b-846a-4c31-8960-6a98a3f13efd.png) of this repository, which most new GitHub users tend to ignore.

**Comment by isaak654** [comment]
The original link at the beginning of the [README.md](https://github.com/blap/SandboxToys2#readme) was included to mention the original discussion from which SandboxToys2 originated. At most, that part could be improved to avoid misunderstandings.

If you want to download the latest release: https://github.com/blap/SandboxToys2/releases 
The same link can be found manually in the [right column](https://user-images.githubusercontent.com/12372772/228072872-0d1ab51b-846a-4c31-8960-6a98a3f13efd.png) of this repository, which most new GitHub users tend to ignore.

**Comment by blap** [comment]
Maybe now is more clear: https://github.com/blap/SandboxToys2/blob/main/README.md
