### ISSUE TITLE
v2.4 changes are not well explained

### ISSUE THREAD

**Issue by isaak654** [blap/SandboxToys2#6]
Release notes for [v2.4](https://github.com/blap/SandboxToys2/releases/tag/v2.4) should provide a clear explanation about the removal of SbieCtrl.exe support: https://github.com/blap/SandboxToys2/issues/4#issuecomment-1486932465

**Comment by blap** [comment]
> Release notes for [v2.4](https://github.com/blap/SandboxToys2/releases/tag/v2.4) should provide a clear explanation about the removal of SbieCtrl.exe support: [#4 (comment)](https://github.com/blap/SandboxToys2/issues/4#issuecomment-1486932465)

Like this? [https://github.com/blap/SandboxToys2/releases/tag/v2.4](url)
